version: '3'

services:
  java:
    image: alexsuf/java
    container_name: java
    restart: no
    environment:
      TZ: Europe/Moscow
    stdin_open: true
    tty: true
    volumes:
      - ./app:/app
